version: "2"
checks:
  argument-count:
    enabled: true
    config:
      threshold: 4
  complex-logic:
    enabled: true
    config:
      threshold: 4
  file-lines:
    enabled: true
    config:
      threshold: 250
  method-complexity:
    enabled: true
    config:
      threshold: 10
  method-count:
    enabled: true
    config:
      threshold: 20
  method-lines:
    enabled: true
    config:
      threshold: 25
  nested-control-flow:
    enabled: true
    config:
      threshold: 4
  return-statements:
    enabled: true
    config:
      threshold: 4
  similar-code:
    enabled: true
    config:
      threshold: 70
  identical-code:
    enabled: true
    config:
      threshold: 50

exclude_patterns:
  - "packages/shared/coverage/**"
  - "node_modules/"
  - "**/node_modules/"
  - "**/*.d.ts"
  - "**/*.test.ts"
  - "**/*.test.tsx"
  - "**/*.spec.ts"
  - "**/*.spec.tsx"
  - "**/dist/"
  - "**/build/"
  - "**/*.config.js"
  - "**/*.config.ts"
  - ".github/"
  - ".vscode/"
  - ".devcontainer/"
  - "coverage/"
  - "reports/"
  - ".pnpm-store/"
  - "**/__mocks__/"
  - "**/__tests__/"
  - "**/test/"
  - "**/tests/"
  - "**/coverage/**"
  - "**/.pnpm-store/**"

plugins:
  eslint:
    enabled: true
    channel: "eslint-9"
    config:
      extensions:
        - .js
        - .jsx
        - .ts
        - .tsx
  tslint:
    enabled: true
  sonar-typescript:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        typescript:
          mass_threshold: 45
        javascript:
          mass_threshold: 45
  fixme:
    enabled: true
    config:
      strings:
        - TODO
        - FIXME
        - BUG
        - HACK
        - XXX
  git-legal:
    enabled: true
  markdownlint:
    enabled: true
  shellcheck:
    enabled: true
  nodesecurity:
    enabled: true