version: "2"
checks:
  argument-count:
    enabled: true
    config:
      threshold: 4
  complex-logic:
    enabled: true
    config:
      threshold: 4
  file-lines:
    enabled: true
    config:
      threshold: 250
  method-complexity:
    enabled: true
    config:
      threshold: 10
  method-count:
    enabled: true
    config:
      threshold: 20
  method-lines:
    enabled: true
    config:
      threshold: 25
  nested-control-flow:
    enabled: true
    config:
      threshold: 4
  return-statements:
    enabled: true
    config:
      threshold: 4

exclude_patterns:
  - "node_modules/"
  - "**/*.d.ts"
  - "**/*.test.ts"
  - "**/*.test.tsx"
  - "**/dist/"
  - "**/*.config.js"
  - "**/*.config.ts"

plugins:
  eslint:
    enabled: true
  tslint:
    enabled: true
  sonar-typescript:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        typescript:
          mass_threshold: 45
        javascript:
          mass_threshold: 45